### PR TITLE
BREAKING: Code split SvgIcons

### LINKED ISSUE #880: De-bloat SvgIcon
The index export in SvgIcon is really heavy. When importing it in other projects (like wolverine-frontend) we are not at the moment able to tree-shake it. This leads to that every element that loads an SvgIcon, loads all the icons.

Is it possible to make the icons into dynamic imports without binding ourselves to next?

See also #879

### PR DESCRIPTION
**Pull request by evoX0**
Load SvgIcons lazily. This way, using a single icon from SvgIcon no longer will require you to load all the icons to the client.

If you are currently importing a single SvgIcon directly
```js
import { Star } from '@aller/shiny/lib/atoms/SvgIcon/Star'

<Star />
```

You now have to use it via SvgIcon instead:
```js
import { SvgIcon } from '@aller/shiny/lib/atoms/SvgIcon'

<SvgIcon name="star" />
```

Fixes #880

### CODE REVIEW

**Comment by misund** [comment]
Quick question, Rodion: How will this work in the server render?

**Comment by evoX0** [comment]
I want to check how it will work. I'll set shiny locally

**Comment by evoX0** [comment]
Invariant Violation: ReactDOMServer does not yet support Suspense.
:(

**Comment by misund** [comment]
:(

Hopefully, it's not that far away.

In the mean time, how about something like this?
```js
const icons = {
    star: () => import('path/to/Star'),
    circle: () => import('path/to/Circle')
}

SvgIcon = ({name, ...rest}) => {
    const resolveIcon = icons[name] || noop
    const Icon = resolveIcon()

    return <Icon {...rest} />
}
```

**Comment by evoX0** [comment]
Since backNav: () => import('./BackNav'),
will return a promise, we must resolve it in return statement or create a class and pass it to state.
I just use require instead.
@misund need your advice

**Comment by misund** [comment]
How is this?
```js
const toReturn = await resolveModule();
return Promise.resolve(toReturn.default);

**Comment by evoX0** [comment]
Something like that  https://github.com/dbmedialab/shiny/pull/944/commits/0f6000a8abf81df0cf76a0b04aead41a3cda07a3

**Comment by misund** [comment]
Yeah, now we're getting there! Is it working?

Couple of minor things:
- why are we doing this in componentDidMount? That's a bit late. Is it to handle the asynchronicity from the promises?
- And why are we changing the logic of which props get sent through to the icon and the wrapper? That's not related to this change. If anything, we should get rid of the wrapper, not making it more complicated.

**Comment by misund** [comment]
Good work so far

**Comment by evoX0** [comment]
yep, its working.
I can set initialize state to willMount.
about changing the logic, can you clarify? because I thought svgIconwrapper looks like it was. :)

**Comment by misund** [comment]
> about changing the logic, can you clarify? because I thought svgIconwrapper looks like it was. :)

My mistake – I was apparently comparing to a refactor-branch instead of master. Nevermind!

**Pull request merged**
