### PR TITLE
Add postinstall step.

### PR DESCRIPTION
**Pull request by engvik**
Since we're going to import these files as a node module in another project, we need to transpile the code.

Since we're not using npm, we can't use the `prepublish` hook. The reasonable way to do this then, is using the `postinstall` hook.

### CODE REVIEW

**Comment by misund** [comment]
Why can't we use the source directly and build in the webapp instead?

I also wouldn't be so quick to disregard npm.

**Comment by engvik** [comment]
I find it very strange to have to compile something inside node_modules, it's really not the common way to do this.

Okay, open source it then? @SindreSvendby said private NPM was very expencive.

**Comment by engvik** [comment]
Btw., we already had this discussion regarding `am-assets`.

You won't get any compiled code in the repository.

**Comment by engvik** [comment]
If we're open sourcing, simply change `postinstall` to `prepublish` in package.json

**Pull request merged**
