### PR TITLE
fix(NumberedListItem): Move ::before to element instead of child

### LINKED ISSUE #399: <span> in NumberedListItem
`NumberedListItem` component looks like this now:
```
const NumberedListItem = ({ children }) => (
	<NumberedListItemWrapper>
		<span>{children}</span>
	</NumberedListItemWrapper>
);
```

Is `<span>` really required though? (It doesn't work without it)

Need investigation

### PR DESCRIPTION
**Pull request by misund**
Fixes #399

#### Please tick a box ###
- [x] **fix** _(A bug fix_)

#### If you're adding a feature, is it documented in a storybook story?
- [x] Yes

#### Are the components you're working on reusable between brands?
- [x] Yes _(Using variables that are defined in the default theme)_

#### If you're creating markup, did you add proper semantics? 
- [x] Not applicable

### CODE REVIEW

**Comment by misund** [comment]
It's not covered in the storybook, though. Maybe we should add it?

The old way of doing it (styling `> *::before`) is written the way that it is because the oppskrift database contains entries where several `<p>` elements would be mapped to a single `NumberedListItem`, but we want them to be listed out as distinguished steps of a recipe.

**Comment by misund** [comment]
We would still support that by simply removing the span, but then we cannot allow plain text as children.

**Comment by tnlitv** [comment]
Hmm, I didn't know that we can have several <p> in one response. Anyway, this case is handled on oppskrift. Do other projects have the same issue? 
I mean, I wanted to make NumberedList reusable, but simple. If other projects have same thing with html in database, it makes sense to me that we set `<span>` contents with `dangerouslySetInnerHtml`

**Comment by misund** [comment]
Here's a different approach, but this does not support pure text input.

**Comment by misund** [comment]
> Anyway, this case is handled on oppskrift.

So we don't have to support several p's in one NumberedListItem as far as oppskrift is concerned?

> Do other projects have the same issue?

No

**Comment by tnlitv** [comment]
We could set inner html on span, and support both plain text and html nodes :)

**Comment by misund** [comment]
I seem to be babbling. There cannot be several p's in a single NumberedListItem - if it were, it would not work with the span, because the before selector hits the span instead of the p.

I'll rebase away the latest commit.

**Comment by misund** [comment]
There we go. This version supports both plain text and html nodes, and does not use either evil extra wrapper spans or dangerouslyInsertInnerHTML.

**Pull request merged**
